package org.leo.ddb.utils.exceptions;

public enum Issue {
    UNKNOWN_ERROR,
    JSON_SERIALIZE_ERROR,
    INVALID_JSON,
    INCORRECT_MODEL_ANNOTATION,
    NO_HANDLER_FOR_MESSAGE_TYPE,
    MISSING_EMPTY_CONSTRUCTOR,
    RECORD_ALREADY_EXISTS,
    OPTIMISTIC_LOCK_ERROR,
    EMPTY_MESSAGE_BODY
}
